version: '3.7'
services:
    glances:
        restart: always
        ports:
            - 61208-61209:61208-61209
        container_name: glances
        environment:
            - GLANCES_OPT=-w
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        pid: host
        image: nicolargo/glances:latest
